# Generated by Django 4.1.2 on 2022-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('num_events', models.IntegerField()),
                ('energy', models.CharField(max_length=50)),
                ('geometry', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
