"""
Django settings for bee project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import socket
HOST_NAME = socket.gethostname()
SITE_LOCAL = SITE_BNL = SITE_TWISTER = False
DATA_DIR = 'nothing'
if HOST_NAME.startswith('lycastus'):
    SITE_BNL = True
    DATA_DIR = '../../public_html/examples'
    DEBUG = False
    ALLOWED_HOSTS = ['phy.bnl.gov', 'lycastus.phy.bnl.gov']
elif HOST_NAME.startswith('twister'):
    SITE_TWISTER = True
    DEBUG = True
    DATA_DIR = '../../public_html/examples'
    ALLOWED_HOSTS = ['phy.bnl.gov', 'twister.phy.bnl.gov']
else:
    SITE_LOCAL = True
    DATA_DIR = '../wire-cell'
    DEBUG = True
    ALLOWED_HOSTS = []

import configparser
conf = configparser.RawConfigParser()
conf.read(BASE_DIR / 'bee/bee.conf')
SECRET_KEY = conf.get('common', 'SECRET_KEY')
# print(SECRET_KEY)
TEMPLATE_DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'particles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# needed for django 4.x
CSRF_TRUSTED_ORIGINS = ['https://www.phy.bnl.gov']

ROOT_URLCONF = 'bee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bee.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = BASE_DIR / '../bee3-static'
if SITE_LOCAL:
    STATIC_URL = 'static/'
elif SITE_BNL:
    # STATIC_URL = 'http://www.phy.bnl.gov/wire-cell/bee-static/'
    STATIC_URL = '/wire-cell/bee-static/'
elif SITE_TWISTER:
    STATIC_URL = '/twister/static/'

# path to store uploaded filels
if SITE_LOCAL:
    MEDIA_ROOT = BASE_DIR / 'tmp'
else:
    MEDIA_ROOT = conf.get('common', 'MEDIA_ROOT')

SITE_ID = 1
